"""Storage-neutral identity value used by authentication adapters."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class UserIdentity:
    id: str
    email: str
    legacy_owner: bool = False


class AuthStorageUnavailable(RuntimeError):
    """The server-side authentication database is temporarily unavailable."""


class AuthRepository(Protocol):
    """Storage-neutral contract consumed by the Web authentication service."""

    def user_by_email(self, email: str) -> UserIdentity | None: ...

    def user_by_id(self, user_id: str) -> UserIdentity | None: ...

    def password_hash(self, password: str) -> str: ...

    def verify_password(self, password: str, password_hash: str) -> bool: ...

    def insert_challenge(
        self,
        email: str,
        purpose: str,
        code: str,
        ip_address: str | None,
        *,
        ttl_seconds: int = 600,
    ) -> None: ...

    def can_send(self, email: str, purpose: str, ip_address: str | None) -> tuple[bool, int]: ...

    def consume_limit(self, key: str, action: str, limit: int, window_seconds: int) -> bool: ...

    def register_user(self, email: str, code: str, password: str) -> UserIdentity: ...

    def authenticate(self, email: str, password: str) -> UserIdentity | None: ...

    def reset_password(self, email: str, code: str, password: str) -> UserIdentity: ...

    def create_session(self, user_id: str, kind: str, *, ttl_seconds: int = 2_592_000) -> str: ...

    def resolve_token(self, token: str) -> tuple[UserIdentity, str] | None: ...

    def revoke_token(self, token: str) -> None: ...

    def revoke_user_sessions(self, user_id: str) -> None: ...

    def start_device(self, server_url: str, *, ttl_seconds: int = 600) -> tuple[str, str, int]: ...

    def device_info(self, browser_secret: str) -> dict[str, object] | None: ...

    def approve_device(self, browser_secret: str, user_id: str, approved: bool) -> bool: ...

    def poll_device(self, poll_secret: str) -> tuple[str, str | None]: ...

    def metadata(self, key: str) -> str | None: ...

    def set_metadata(self, key: str, value: str) -> None: ...

    def ping(self) -> None: ...

    def close(self) -> None: ...
