"""Windows-native sandbox subsystem."""

from .admission import AggregateLimits, ResourceRequest, SandboxAdmission, SandboxAdmissionTimeout
from .approvals import ApprovalDecision, ApprovalGrant, ApprovalStore, authorization_hash
from .broker import BrokerManagedProcess, BrokerStatus, WindowsBrokerClient
from .broker_service import (
    BROKER_VERSION,
    AccountLease,
    AccountPool,
    BrokerConfiguration,
    DpapiKeyStore,
    UserAccountPools,
    WindowsBrokerService,
    WindowsDpapiProvider,
    WindowsNamedPipeServer,
    WindowsServiceInstaller,
)
from .errors import (
    BrokerInstallationError,
    BrokerInstallFailureCode,
    SandboxCleanupPending,
    SandboxError,
    SandboxFailureCode,
    SandboxInitializationError,
    SandboxPolicyError,
    SandboxResourceExceeded,
)
from .launcher import SandboxLauncher
from .manifest import ResourceManifest, ResourceRecord
from .native_broker_adapter import WfpController, WindowsNativeBrokerAdapter
from .native_windows import (
    WindowsAccountManager,
    WindowsAclManager,
    WindowsJobObject,
    WindowsPowerShellWfpController,
    WindowsRestrictedTokenFactory,
    WindowsSandboxAccount,
    windows_pipe_security_attributes,
    windows_service_sid,
)
from .policy import (
    FileAccessMode,
    NetworkMode,
    NetworkRule,
    PermissionMode,
    ResourceLimits,
    SandboxJobContext,
    SandboxLimits,
    SandboxPolicy,
    TerminalKind,
    ensure_disk_reserve,
    normalize_permission_mode,
    resolve_network_rules,
)
from .reclaimer import SandboxResourceReclaimer
from .resources import NullResourceProvider, ResourceMonitor, ResourceUsage

__all__ = [
    "ApprovalDecision",
    "ApprovalGrant",
    "ApprovalStore",
    "BrokerInstallFailureCode",
    "BrokerInstallationError",
    "AccountLease",
    "AccountPool",
    "AggregateLimits",
    "BrokerStatus",
    "BROKER_VERSION",
    "BrokerConfiguration",
    "BrokerManagedProcess",
    "DpapiKeyStore",
    "FileAccessMode",
    "NetworkMode",
    "NetworkRule",
    "NullResourceProvider",
    "PermissionMode",
    "ResourceMonitor",
    "ResourceLimits",
    "ResourceManifest",
    "ResourceRecord",
    "ResourceRequest",
    "ResourceUsage",
    "SandboxCleanupPending",
    "SandboxAdmission",
    "SandboxAdmissionTimeout",
    "SandboxError",
    "SandboxFailureCode",
    "SandboxInitializationError",
    "SandboxLauncher",
    "SandboxJobContext",
    "SandboxLimits",
    "SandboxPolicy",
    "SandboxPolicyError",
    "SandboxResourceExceeded",
    "SandboxResourceReclaimer",
    "TerminalKind",
    "WindowsBrokerClient",
    "WindowsBrokerService",
    "WindowsDpapiProvider",
    "WindowsNamedPipeServer",
    "WindowsServiceInstaller",
    "WindowsAccountManager",
    "WindowsAclManager",
    "WindowsJobObject",
    "WindowsNativeBrokerAdapter",
    "WindowsPowerShellWfpController",
    "WindowsRestrictedTokenFactory",
    "WindowsSandboxAccount",
    "windows_pipe_security_attributes",
    "windows_service_sid",
    "WfpController",
    "UserAccountPools",
    "authorization_hash",
    "normalize_permission_mode",
    "resolve_network_rules",
    "ensure_disk_reserve",
]
